// <auto-generated />
using System;
using Base.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Base.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501171333_AddDataInUserTable")]
    partial class AddDataInUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Base.Domain.Entities.Attendence", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Attendences");
                });

            modelBuilder.Entity("Base.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Base.Domain.Entities.DepartmentLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("LevelId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentLevel");
                });

            modelBuilder.Entity("Base.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Base.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e4b2f91d-9e12-4f4a-b3db-1b58fca15e66",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c8298a9-982f-4d9d-a632-55f7d148f735",
                            Email = "admin@Base.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            ImageUrl = "profiles/Default-Image.jpg",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NationalId = "12345678901234",
                            NormalizedEmail = "ADMIN@BASE.COM",
                            NormalizedUserName = "ADMIN@BASE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f3a18b3-c453-4a3a-b2e3-57f2e0429f50",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "admin@Base.com"
                        },
                        new
                        {
                            Id = "683211b1-1125-42a1-b148-a606a4ca4df3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3c8f4ef-c9ab-49b5-9b16-06f17aa7668a",
                            Email = "Ahmed12@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "احمد مصطفي",
                            ImageUrl = "profiles/df4fb389-64ed-486e-be7d-722771b6e3bc.jpeg",
                            LastName = "محمد الامير",
                            LockoutEnabled = false,
                            NationalId = "30305521354688",
                            NormalizedEmail = "AHMED12@GMAIL.COM",
                            NormalizedUserName = "AHMED12@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01024866094",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46e17415-53e4-4e26-8ce4-3b9f91a4ebcd",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Ahmed12@gmail.com"
                        },
                        new
                        {
                            Id = "df2ea217-2e82-48b9-9442-47556c1a9403",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e09e586-695e-44ad-86a9-f7b49ba3552b",
                            Email = "Ali@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ايمان ايمن",
                            ImageUrl = "profiles/Outdoor Portraits — San Francisco Bay Area's Premier Personal Brand and Headshot Photographer _ Alpa.jpeg",
                            LastName = "السيد المتولي",
                            LockoutEnabled = false,
                            NationalId = "30308795612367",
                            NormalizedEmail = "ALI@GMAIL.COM",
                            NormalizedUserName = "ALI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01134409876",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "287317a5-2b4e-4193-ade4-9b03c843b021",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Ali@gmail.com"
                        },
                        new
                        {
                            Id = "6b9b3e85-ce32-4944-9a46-601bb2b40000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a61c81ae-cdb2-4c92-ae17-75247a4cb5cb",
                            Email = "Hassan44@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "اية محمد",
                            ImageUrl = "profiles/Friendly Professional Business Headshot.jpeg",
                            LastName = "علي محمد",
                            LockoutEnabled = false,
                            NationalId = "30306729061246",
                            NormalizedEmail = "HASSAN4412@GMAIL.COM",
                            NormalizedUserName = "HASSAN4412@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01079945073",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33fe0c4e-09d7-4b8b-a625-7cf0651fb90e",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Hassan44@gmail.com"
                        },
                        new
                        {
                            Id = "fc4df06f-05c2-4751-96c1-8040f2761b7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30d973bd-092f-4869-ac70-0b1004519b48",
                            Email = "Mohamed@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "سارة",
                            ImageUrl = "profiles/82ebaf90-31fe-40ef-8358-99823ce3881d.jpeg",
                            LastName = "ابوزيد",
                            LockoutEnabled = false,
                            NationalId = "30309871265308",
                            NormalizedEmail = "MOHAMED@GMAIL.COM",
                            NormalizedUserName = "MOHAMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01084670325",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a5413d0-0b02-48f8-a24f-16b929d0af74",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Mohamed@gmail.com"
                        },
                        new
                        {
                            Id = "7c30ae16-67eb-4ff2-858f-70aa79aaa3c4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0a0bc059-4d5d-45dc-98dc-5e557d7aa1c1",
                            Email = "Maher@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "سارة ثروت",
                            ImageUrl = "profiles/Rajan Velu.jpeg",
                            LastName = "موسي",
                            LockoutEnabled = false,
                            NationalId = "30301937508274",
                            NormalizedEmail = "MAHER@GMAIL.COM",
                            NormalizedUserName = "MAHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01208173649",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04a9f78c-43b0-4a6f-bb40-c161adb30b23",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Maher@gmail.com"
                        },
                        new
                        {
                            Id = "ce47a5ab-df14-416a-b500-9b544fa666a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d48db4f-16d7-418b-b97f-dbfe8616af56",
                            Email = "Nader@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "سيف الدين",
                            ImageUrl = "profiles/Mari Juliano.jpeg",
                            LastName = "حسام سلامة",
                            LockoutEnabled = false,
                            NationalId = "303020837616543",
                            NormalizedEmail = "NADER@GMAIL.COM",
                            NormalizedUserName = "NADER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01147893547",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e68c1657-3cb1-4097-a45f-27c1a655c81f",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Nader@gmail.com"
                        },
                        new
                        {
                            Id = "249aa6c5-d578-4517-8a42-48f24a7d959e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7ed49bc-72fb-42be-afc5-fbd0351bd759",
                            Email = "Khaled2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "زياد محمد",
                            ImageUrl = "profiles/MEN - Location - Headshot Photography by Brandon Tabiolo.jpeg",
                            LastName = "الشحات",
                            LockoutEnabled = false,
                            NationalId = "30301920482846",
                            NormalizedEmail = "KHALED2@GMAIL.COM",
                            NormalizedUserName = "KHALED2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01293749183",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f85433e6-bf5b-4ffc-9d02-3a7cc9938547",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Khaled2@gmail.com"
                        },
                        new
                        {
                            Id = "49a438ba-672d-41d5-97ba-5536ffbec2a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9773109-8364-4c61-a5d4-9fe85a58c0f4",
                            Email = "Kareem@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "شهد عصمت فؤاد",
                            ImageUrl = "profiles/Why I Mainly Photograph in Portrait Orientation for Actors' Headshots.jpeg",
                            LastName = "بكر",
                            LockoutEnabled = false,
                            NationalId = "303092689146845",
                            NormalizedEmail = "KAREEM@GMAIL.COM",
                            NormalizedUserName = "KAREEM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01024860821",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aed0822d-8180-49b3-85cc-a4f5a33a3b56",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Kareem@gmail.com"
                        },
                        new
                        {
                            Id = "bf2ee728-59af-45ec-9b70-e5f5e27eef8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43d7bf34-bc3a-4d7f-841e-f1dfd028303d",
                            Email = "Halem@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "شهد حسن",
                            ImageUrl = "profiles/Gorgeous smile of Alexis Petit.jpeg",
                            LastName = "عبدااللاه حسن",
                            LockoutEnabled = false,
                            NationalId = "30308391092836",
                            NormalizedEmail = "HALEM@GMAIL.COM",
                            NormalizedUserName = "HALEM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01049182640",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "999faa1d-9041-4c56-888c-42b8286d68b7",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Halem@gmail.com"
                        },
                        new
                        {
                            Id = "cb3cb7ca-1921-49fd-a11e-600b351b3df2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c76ae4f3-37a2-4707-b71b-f5d99f6f50da",
                            Email = "Salma@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "عبدالله وائل",
                            ImageUrl = "profiles/Women in Business.jpeg",
                            LastName = "حافظ",
                            LockoutEnabled = false,
                            NationalId = "30302901738376",
                            NormalizedEmail = "SALMA@GMAIL.COM",
                            NormalizedUserName = "SALMA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01029836539",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2121aa48-49d8-4b1e-841e-48a7e61b0863",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Salma@gmail.com"
                        },
                        new
                        {
                            Id = "cb3cb7ca-1921-49fd-a11e-600b351b3df3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f58fbbd5-a0d4-460c-bc0d-5afb9a0adb63",
                            Email = "Jesseyd@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "منة الله محمد",
                            ImageUrl = "profiles/9151a7a4-4fc2-4bb0-a427-f97f4127e661.jpeg",
                            LastName = "مصطفي",
                            LockoutEnabled = false,
                            NationalId = "40415678901625",
                            NormalizedEmail = "JESSEYD@GMAIL.COM",
                            NormalizedUserName = "JESSEYD@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "07022670816",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4dd9dcd-8ef8-40fa-b1ac-6a6caa133079",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Jesseyd@gmail.com"
                        },
                        new
                        {
                            Id = "5d577849-97d1-4984-bf96-6fee7d08c8be",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edb44c87-00c3-488a-9b74-2fc632b48bfc",
                            Email = "Marry@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "مؤمن رفعت",
                            ImageUrl = "profiles/468f9794-778b-429f-bea8-b7440810819d.jpeg",
                            LastName = "كمال",
                            LockoutEnabled = false,
                            NationalId = "40423109753269",
                            NormalizedEmail = "MARRY@GMAIL.COM",
                            NormalizedUserName = "MARRY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "02029837399",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e27dc6f7-4bf0-44a1-a3fb-8b3e5239e87f",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Marry@gmail.com"
                        },
                        new
                        {
                            Id = "f89bca4a-8fc9-4259-a46d-22562907c27f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c615d822-a4fc-4a3a-8b23-b4b6c155b96a",
                            Email = "Mark@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "يوسف محمد",
                            ImageUrl = "profiles/44050f40-662d-408b-9dda-9e3271d7c36e.jpeg",
                            LastName = "حسن الشحات",
                            LockoutEnabled = false,
                            NationalId = "4042098715635491",
                            NormalizedEmail = "MARK@GMAIL.COM",
                            NormalizedUserName = "MARK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "070901468297",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6909260d-6430-4133-868e-9091e01fe56f",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Mark@gmail.com"
                        },
                        new
                        {
                            Id = "cb3cb7ca-1921-49fd-a11e-600b351b3df4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f58fbbd5-a0d4-460c-bc0d-5afb9a0adb63",
                            Email = "Jessey@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "نانسي عصام",
                            ImageUrl = "profiles/9151a7a4-4fc2-4bb0-a427-f97f4127e661.jpeg",
                            LastName = "محمد السيد",
                            LockoutEnabled = false,
                            NationalId = "40415678901625",
                            NormalizedEmail = "JESSEY@GMAIL.COM",
                            NormalizedUserName = "JESSEY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "07022670816",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4dd9dcd-8ef8-40fa-b1ac-6a6caa133079",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Jessey@gmail.com"
                        },
                        new
                        {
                            Id = "8766c317-1eaa-468a-b34d-59790c8eb915",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4986d9a-0ff6-4ecb-9f51-b8bb5dc826e4",
                            Email = "Rana2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ندي نسيم",
                            ImageUrl = "profiles/2edc3141-b4cd-411d-9136-33440bbb1c03.jpeg",
                            LastName = "علي احمد",
                            LockoutEnabled = false,
                            NationalId = "30304597102873",
                            NormalizedEmail = "RANA2@GMAIL.COM",
                            NormalizedUserName = "RANA2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01028649032",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5e74c9d-fe75-442e-a90e-6400f6a2f0c7",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Rana2@gmail.com"
                        },
                        new
                        {
                            Id = "a12bc34d-5e6f-7g8h-9i0j-1k2l3m4n5o6p",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d726e933-b5gd-5b4b-9c34-c5c7d166c97h",
                            Email = "Ahmed@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "أحمد علي",
                            ImageUrl = "profiles/55060g50-773e-519c-0eef-0f4382e8d47f.jpg",
                            LastName = "عبد الرحمن",
                            LockoutEnabled = false,
                            NationalId = "1234567890123456",
                            NormalizedEmail = "AHMED@GMAIL.COM",
                            NormalizedUserName = "AHMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "071234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7908371e-7541-5244-979f-9192e12fe67g",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Ahmed@gmail.com"
                        },
                        new
                        {
                            Id = "b23cd45e-6f7g-8h9i-0j1k-2l3m4n5o6p7q",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e837f044-c6he-6c5c-0d45-d6d8e277d08i",
                            Email = "Sara@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "سارة محمد",
                            ImageUrl = "profiles/66071h61-884f-62ad-1ffg-1g5493f9e58g.png",
                            LastName = "عبد الله",
                            LockoutEnabled = false,
                            NationalId = "2345678901234567",
                            NormalizedEmail = "SARA@GMAIL.COM",
                            NormalizedUserName = "SARA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "072345678901",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8019482f-8652-6355-08ag-0283f23gf78h",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Sara@gmail.com"
                        },
                        new
                        {
                            Id = "c34de56f-7g8h-9i0j-1k2l-3m4n5o6p7q8r",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f948g155-d7if-7d6d-1e56-e7e9f388e19j",
                            Email = "Maryam@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "مريم أحمد",
                            ImageUrl = "profiles/77082i72-995g-73be-2ggh-2h65a4g0f69h.jpeg",
                            LastName = "عمر فاروق",
                            LockoutEnabled = false,
                            NationalId = "3456789012345678",
                            NormalizedEmail = "MARYAM@GMAIL.COM",
                            NormalizedUserName = "MARYAM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "073456789012",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9120593g-9763-7466-19bh-1394g34hg89i",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Maryam@gmail.com"
                        },
                        new
                        {
                            Id = "d45ef67g-8h9i-0j1k-2l3m-4n5o6p7q8r9s",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "g059h266-e8jg-8e7e-2f67-f8f0g499f20k",
                            Email = "Khaled@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "خالد محمود",
                            ImageUrl = "profiles/88093j83-006h-84cf-3hhi-3i76b5h1g70i.jpg",
                            LastName = "سعيد عبد العزيز",
                            LockoutEnabled = false,
                            NationalId = "4567890123456789",
                            NormalizedEmail = "KHALED@GMAIL.COM",
                            NormalizedUserName = "KHALED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "074567890123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02316a4h-0874-8577-20ci-2405h45ih90j",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Khaled@gmail.com"
                        },
                        new
                        {
                            Id = "e56fg78h-9i0j-1k2l-3m4n-5o6p7q8r9s0t",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "h16ai377-f9kh-9f8f-3g78-g9g1h5a0g31l",
                            Email = "Nora@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "نورا حسن",
                            ImageUrl = "profiles/99004k94-117i-95dg-4iij-4j87c6i2h81j.png",
                            LastName = "محمود عبد الرحيم",
                            LockoutEnabled = false,
                            NationalId = "5678901234567890",
                            NormalizedEmail = "NORA@GMAIL.COM",
                            NormalizedUserName = "NORA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "075678901234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13427b5i-1985-9688-31dj-3516i56ji01k",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Nora@gmail.com"
                        },
                        new
                        {
                            Id = "f67gh89i-0j1k-2l3m-4n5o-6p7q8r9s0t1u",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "i27bj488-g0li-0g9g-4h89-h0h2i6b1h42m",
                            Email = "Omar@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "عمر خالد",
                            ImageUrl = "profiles/00115l05-228j-06eh-5jjk-5k98d7j3i92k.jpeg",
                            LastName = "ياسر محمد",
                            LockoutEnabled = false,
                            NationalId = "6789012345678901",
                            NormalizedEmail = "OMAR@GMAIL.COM",
                            NormalizedUserName = "OMAR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "076789012345",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24538c6j-2096-0799-42ek-4627j67kj12l",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Omar@gmail.com"
                        },
                        new
                        {
                            Id = "g78hi90j-1k2l-3m4n-5o6p-7q8r9s0t1u2v",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "j38ck599-h1mj-1h0h-5i90-i1i3j7c2i53n",
                            Email = "Fatima@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "فاطمة إبراهيم",
                            ImageUrl = "profiles/11226m16-339k-17fi-6kkl-6l09e8k4j03l.jpg",
                            LastName = "علي محسن",
                            LockoutEnabled = false,
                            NationalId = "7890123456789012",
                            NormalizedEmail = "FATIMA@GMAIL.COM",
                            NormalizedUserName = "FATIMA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "077890123456",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35649d7k-3107-1800-53fl-5738k78lk23m",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Fatima@gmail.com"
                        },
                        new
                        {
                            Id = "h89ij01k-2l3m-4n5o-6p7q-8r9s0t1u2v3w",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "k49dl6aa-i2nk-2i1i-6j01-j2j4k8d3j64o",
                            Email = "Yasser@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ياسر عبد الله",
                            ImageUrl = "profiles/22337n27-440l-28gj-7llm-7m10f9l5k14m.png",
                            LastName = "مصطفى أحمد",
                            LockoutEnabled = false,
                            NationalId = "8901234567890123",
                            NormalizedEmail = "YASSER@GMAIL.COM",
                            NormalizedUserName = "YASSER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "078901234567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46750e8l-4218-2911-64gm-6849l89ml34n",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Yasser@gmail.com"
                        },
                        new
                        {
                            Id = "i90jk12l-3m4n-5o6p-7q8r-9s0t1u2v3w4x",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "l50em7bb-j3ol-3j2j-7k12-k3k5l9e4k75p",
                            Email = "Aya@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "آية محمد",
                            ImageUrl = "profiles/33448o38-551m-39hk-8mmn-8n21g0m6l25n.jpeg",
                            LastName = "خالد عبد الكريم",
                            LockoutEnabled = false,
                            NationalId = "9012345678901234",
                            NormalizedEmail = "AYA@GMAIL.COM",
                            NormalizedUserName = "AYA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "079012345678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57861f9m-5329-3022-75hn-7950m90nm45o",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Aya@gmail.com"
                        },
                        new
                        {
                            Id = "j01kl23m-4n5o-6p7q-8r9s-0t1u2v3w4x5y",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "m61fn8cc-k4pm-4k3k-8l23-l4l6m0f5l86q",
                            Email = "Mustafa@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "مصطفى علي",
                            ImageUrl = "profiles/44559p49-662n-40il-9nno-9o32h1n7m36o.jpg",
                            LastName = "حسين محمود",
                            LockoutEnabled = false,
                            NationalId = "0123456789012345",
                            NormalizedEmail = "MUSTAFA@GMAIL.COM",
                            NormalizedUserName = "MUSTAFA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "070123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "68972g0n-6430-4133-86io-8061n01on56p",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Mustafa@gmail.com"
                        },
                        new
                        {
                            Id = "k12lm34n-5o6p-7q8r-9s0t-1u2v3w4x5y6z",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "n72go9dd-l5qn-5l4l-9m34-m5m7n1g6m97r",
                            Email = "Hanaa@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "هناء عبد الرحمن",
                            ImageUrl = "profiles/55660q50-773o-51jm-0oop-0p43i2o8n47p.png",
                            LastName = "سعيد محمد",
                            LockoutEnabled = false,
                            NationalId = "1234567890123450",
                            NormalizedEmail = "HANAA@GMAIL.COM",
                            NormalizedUserName = "HANAA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "071234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79083h1o-7541-5244-97jp-9172o12po67q",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Hanaa@gmail.com"
                        },
                        new
                        {
                            Id = "l23mn45o-6p7q-8r9s-0t1u-2v3w4x5y6z7a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "o83hp0ee-m6ro-6m5m-0n45-n6n8o2h7n08s",
                            Email = "Abdelrahman@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "عبد الرحمن عماد",
                            ImageUrl = "profiles/66771r61-884p-62kn-1ppq-1q54j3p9o58q.jpeg",
                            LastName = "ياسر فؤاد",
                            LockoutEnabled = false,
                            NationalId = "2345678901234501",
                            NormalizedEmail = "ABDELRAHMAN@GMAIL.COM",
                            NormalizedUserName = "ABDELRAHMAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "072345678901",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80194i2p-8652-6355-08kq-0283p23qp78r",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Abdelrahman@gmail.com"
                        },
                        new
                        {
                            Id = "m34no56p-7q8r-9s0t-1u2v-3w4x5y6z7a8b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "p94iq1ff-n7sp-7n6n-1o56-o7o9p3i8o19t",
                            Email = "Iman@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "إيمان حسين",
                            ImageUrl = "profiles/77882s72-995q-73lo-2qqr-2r65k4q0p69r.jpg",
                            LastName = "محمود عبد الله",
                            LockoutEnabled = false,
                            NationalId = "3456789012345012",
                            NormalizedEmail = "IMAN@GMAIL.COM",
                            NormalizedUserName = "IMAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "073456789012",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91205j3q-9763-7466-19lr-1394q34qr89s",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Iman@gmail.com"
                        },
                        new
                        {
                            Id = "n45op67q-8r9s-0t1u-2v3w-4x5y6z7a8b9c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "q05jr2gg-o8tq-8o7o-2p67-p8p0q4j9p20u",
                            Email = "MohamedAmin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "محمد أمين",
                            ImageUrl = "profiles/88993t83-006r-84mp-3rrs-3s76l5r1q70s.png",
                            LastName = "عبد الحميد سليمان",
                            LockoutEnabled = false,
                            NationalId = "4567890123450123",
                            NormalizedEmail = "MOHAMEDAMIN@GMAIL.COM",
                            NormalizedUserName = "MOHAMEDAMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "074567890123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02316k4r-0874-8577-20ms-2405r45rs90t",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "MohamedAmin@gmail.com"
                        },
                        new
                        {
                            Id = "o56pq78r-9s0t-1u2v-3w4x-5y6z7a8b9c0d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "r16ks3hh-p9ur-9p8p-3q78-q9q1r5k0q31v",
                            Email = "Rana@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "رنا وليد",
                            ImageUrl = "profiles/99004u94-117s-95nq-4sst-4t87m6s2r81t.jpeg",
                            LastName = "عبد الغني محمد",
                            LockoutEnabled = false,
                            NationalId = "5678901234501234",
                            NormalizedEmail = "RANA@GMAIL.COM",
                            NormalizedUserName = "RANA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "075678901234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13427l5s-1985-9688-31nt-3516s56st01u",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Rana@gmail.com"
                        },
                        new
                        {
                            Id = "p67qr89s-0t1u-2v3w-4x5y-6z7a8b9c0d1e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "s27lt4ii-q0vs-0q9q-4r89-r0r2s6l1r42w",
                            Email = "Waleed@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "وليد كمال",
                            ImageUrl = "profiles/00115v05-228t-06or-5ttu-5u98n7t3s92u.jpg",
                            LastName = "حسن عبد الرحمن",
                            LockoutEnabled = false,
                            NationalId = "6789012345012345",
                            NormalizedEmail = "WALEED@GMAIL.COM",
                            NormalizedUserName = "WALEED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "076789012345",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24538m6t-2096-0799-42ou-4627t67tu12v",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Waleed@gmail.com"
                        },
                        new
                        {
                            Id = "q78rs90t-1u2v-3w4x-5y6z-7a8b9c0d1e2f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "t38mu5jj-r1wt-1r0r-5s90-s1s3t7m2s53x",
                            Email = "Salma3@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "سلمى أحمد",
                            ImageUrl = "profiles/11226w16-339u-17ps-6uuv-6v09o8u4t03v.png",
                            LastName = "عبد العزيز محمد",
                            LockoutEnabled = false,
                            NationalId = "7890123450123456",
                            NormalizedEmail = "SALMA3@GMAIL.COM",
                            NormalizedUserName = "SALMA3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "077890123456",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35649n7u-3107-1800-53pv-5738u78uv23w",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Salma3@gmail.com"
                        },
                        new
                        {
                            Id = "r89st01u-2v3w-4x5y-6z7a-8b9c0d1e2f3g",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u49nv6kk-s2xu-2s1s-6t01-t2t4u8n3t64y",
                            Email = "Abdelaziz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "عبد العزيز محمود",
                            ImageUrl = "profiles/22337x27-440v-28qt-7vvw-7w10p9v5u14w.jpeg",
                            LastName = "خالد سعيد",
                            LockoutEnabled = false,
                            NationalId = "8901234501234567",
                            NormalizedEmail = "ABDELAZIZ@GMAIL.COM",
                            NormalizedUserName = "ABDELAZIZ@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "078901234567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46750o8v-4218-2911-64qw-6849v89vw34x",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Abdelaziz@gmail.com"
                        },
                        new
                        {
                            Id = "s90tu12v-3w4x-5y6z-7a8b-9c0d1e2f3g4h",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "v50ow7ll-t3yv-3t2t-7u12-u3u5v9o4u75z",
                            Email = "Mona@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "منى حسام",
                            ImageUrl = "profiles/33448y38-551w-39ru-8wwx-8x21q0w6v25x.jpg",
                            LastName = "مصطفى عبد الله",
                            LockoutEnabled = false,
                            NationalId = "9012345012345678",
                            NormalizedEmail = "MONA@GMAIL.COM",
                            NormalizedUserName = "MONA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "079012345678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57861p9w-5329-3022-75rx-7950w90wx45y",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Mona@gmail.com"
                        },
                        new
                        {
                            Id = "t01uv23w-4x5y-6z7a-8b9c-0d1e2f3g4h5i",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "w61px8mm-u4zw-4u3u-8v23-v4v6w0p5v86a",
                            Email = "Hossam@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "حسام الدين",
                            ImageUrl = "profiles/44559z49-662x-40sv-9xxy-9y32r1x7w36y.png",
                            LastName = "علي محمود",
                            LockoutEnabled = false,
                            NationalId = "0123450123456789",
                            NormalizedEmail = "HOSSAM@GMAIL.COM",
                            NormalizedUserName = "HOSSAM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "070123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "68972q0x-6430-4133-86sy-8061x01xy56z",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Hossam@gmail.com"
                        },
                        new
                        {
                            Id = "10eb7637-95f4-45d2-b200-84dbb188ec41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1ca42846-c687-48a2-9eb4-77fc5f21ae44",
                            Email = "Ramy2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "رامي",
                            ImageUrl = "profiles/16 Black Chefs Changing Food in America (Published 2019).jpeg",
                            LastName = "عزيز",
                            LockoutEnabled = false,
                            NationalId = "30303409168364",
                            NormalizedEmail = "RAMY2@GMAIL.COM",
                            NormalizedUserName = "RAMY2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "011298640281",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f439954d-63d4-4e36-8a5f-827f533cc6a1",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Ramy2@gmail.com"
                        },
                        new
                        {
                            Id = "357c8ce0-ed6e-4979-b1f9-5e0f6e90c9a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d607b523-2920-4ea8-83c4-2103dbb45b0a",
                            Email = "Rola@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "رولا",
                            ImageUrl = "profiles/Before and After_ Transforming Your LinkedIn Profile with AI Headshots.jpeg",
                            LastName = "سامي",
                            LockoutEnabled = false,
                            NationalId = "30306183028747",
                            NormalizedEmail = "ROLA@GMAIL.COM",
                            NormalizedUserName = "ROLA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "012938475601",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eac93f1e-749b-4c66-9783-c46c16b4ffbf",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Rola@gmail.com"
                        },
                        new
                        {
                            Id = "a0e2f1e7-53e5-416f-b0b0-ca4668563233",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a46ec364-f74a-455e-93f2-471913135d05",
                            Email = "Malek@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "مالك",
                            ImageUrl = "profiles/9c12d50d-5cbe-4c75-8bca-cbc57d504a7b.jpeg",
                            LastName = "محمد",
                            LockoutEnabled = false,
                            NationalId = "30308103829384",
                            NormalizedEmail = "MALEK@GMAIL.COM",
                            NormalizedUserName = "MALEK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01283604718",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "16dd3214-5abc-48b6-83cd-df00d21f16dc",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Malek@gmail.com"
                        },
                        new
                        {
                            Id = "52511e3a-0690-45b0-9e52-02667a473b18",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e184b3aa-6771-4830-83f9-b1a59c9676c4",
                            Email = "Magdy@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ماجد",
                            ImageUrl = "profiles/Dallas Headshots Photographer - Willie & Kim Photography.jpeg",
                            LastName = "عبدالله",
                            LockoutEnabled = false,
                            NationalId = "30301789256730",
                            NormalizedEmail = "MAGDY@GMAIL.COM",
                            NormalizedUserName = "MAGDY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01183670178",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fda38b97-da47-40ba-bbe3-702a78f4e009",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Magdy@gmail.com"
                        },
                        new
                        {
                            Id = "52511e3a-0690-45b0-9e52-02667a473c23",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e184b3aa-6771-4830-83f9-b1a59c967aB6",
                            Email = "Yousef@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "يوسف",
                            ImageUrl = "profiles/Dallas Headshots Photographer - Willie & Kim Photography.jpeg",
                            LastName = "سيد",
                            LockoutEnabled = false,
                            NationalId = "30301599256730",
                            NormalizedEmail = "YOUSEF@GMAIL.COM",
                            NormalizedUserName = "YOUSEF@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01283670178",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fda38b97-da47-40ba-bbe3-702a78f4ec15",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Yousef@gmail.com"
                        },
                        new
                        {
                            Id = "u12vw34x-5y6z-7a8b-9c0d-1e2f3g4h5i6j",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "x62ky9nn-v5a1-5v4v-0w34-w6w8x2j7x08b",
                            Email = "Reem@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ريم أحمد",
                            ImageUrl = "profiles/55660a60-889y-51tw-0yyz-0z43s2y8x47z.jpeg",
                            LastName = "عبد الفتاح محمد",
                            LockoutEnabled = false,
                            NationalId = "1122334455667788",
                            NormalizedEmail = "REEM@GMAIL.COM",
                            NormalizedUserName = "REEM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "071122334455",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80294k3y-8653-7366-19tz-1395y45yz90a",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Reem@gmail.com"
                        },
                        new
                        {
                            Id = "v23wx45y-6z7a-8b9c-0d1e-2f3g4h5i6j7k",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "y73lz0oo-w6b2-6w5w-1x45-x7x9y3k8y19c",
                            Email = "Tarek@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "طارق إسماعيل",
                            ImageUrl = "profiles/66771b71-990z-62ux-1zza-1a54t3z9y58a.jpg",
                            LastName = "حسن عبد الوهاب",
                            LockoutEnabled = false,
                            NationalId = "2233445566778899",
                            NormalizedEmail = "TAREK@GMAIL.COM",
                            NormalizedUserName = "TAREK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "072233445566",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91305l4z-9764-8477-20ua-2406z56za01b",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Tarek@gmail.com"
                        },
                        new
                        {
                            Id = "w34xy56z-7a8b-9c0d-1e2f-3g4h5i6j7k8l",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "z84ma1pp-x7c3-7x6x-2y56-y8y0z4l9z20d",
                            Email = "Hadeer@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "هدير كمال",
                            ImageUrl = "profiles/77882c82-001a-73vy-2aab-2b65u4a0z69b.png",
                            LastName = "محمود عبد السلام",
                            LockoutEnabled = false,
                            NationalId = "3344556677889900",
                            NormalizedEmail = "HADEER@GMAIL.COM",
                            NormalizedUserName = "HADEER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "073344556677",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02416m5a-0875-9588-31vb-3517a67ab12c",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Hadeer@gmail.com"
                        },
                        new
                        {
                            Id = "x45yz67a-8b9c-0d1e-2f3g-4h5i6j7k8l9m",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a95nb2qq-y8d4-8y7y-3z67-z9z1a5m0a31e",
                            Email = "Karim@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "كريم سعد",
                            ImageUrl = "profiles/88993d93-112b-84wz-3bbc-3c76v5b1a70c.jpeg",
                            LastName = "علي عبد الرازق",
                            LockoutEnabled = false,
                            NationalId = "4455667788990011",
                            NormalizedEmail = "KARIM@GMAIL.COM",
                            NormalizedUserName = "KARIM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "074455667788",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13527n6b-1986-0699-42wc-4628b78bc23d",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Karim@gmail.com"
                        },
                        new
                        {
                            Id = "y56za78b-9c0d-1e2f-3g4h-5i6j7k8l9m0n",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b06oc3rr-z9e5-9z8z-4a78-a0a2b6n1b42f",
                            Email = "Jana@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "جنى وائل",
                            ImageUrl = "profiles/99004e04-223c-95xa-4ccd-4d87w6c2b81d.jpg",
                            LastName = "محمد عبد الغفار",
                            LockoutEnabled = false,
                            NationalId = "5566778899001122",
                            NormalizedEmail = "JANA@GMAIL.COM",
                            NormalizedUserName = "JANA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "075566778899",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24638o7c-2097-1700-53xd-5739c89cd34e",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Jana@gmail.com"
                        },
                        new
                        {
                            Id = "z67ab89c-0d1e-2f3g-4h5i-6j7k8l9m0n1o",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c17pd4ss-a0f6-0a9a-5b89-b1b3c7o2c53g",
                            Email = "Wael@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "وائل نبيل",
                            ImageUrl = "profiles/00115f15-334d-06yb-5dde-5e98x7d3c92e.png",
                            LastName = "حسين عبد الحليم",
                            LockoutEnabled = false,
                            NationalId = "6677889900112233",
                            NormalizedEmail = "WAEL@GMAIL.COM",
                            NormalizedUserName = "WAEL@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "076677889900",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35749p8d-3108-2811-64ye-6840d90de45f",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Wael@gmail.com"
                        },
                        new
                        {
                            Id = "a78bc90d-1e2f-3g4h-5i6j-7k8l9m0n1o2p",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d28qe5tt-b1g7-1b0b-6c90-c2c4d8p3d64h",
                            Email = "Sama@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "سما عماد",
                            ImageUrl = "profiles/11226g26-445e-17zc-6eef-6f09y8e4d03f.jpeg",
                            LastName = "ياسر عبد المنعم",
                            LockoutEnabled = false,
                            NationalId = "7788990011223344",
                            NormalizedEmail = "SAMA@GMAIL.COM",
                            NormalizedUserName = "SAMA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "077788990011",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46860q9e-4219-3922-75zf-7951e01ef56g",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Sama@gmail.com"
                        },
                        new
                        {
                            Id = "b89cd01e-2f3g-4h5i-6j7k-8l9m0n1o2p3q",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e39rf6uu-c2h8-2c1c-7d01-d3d5e9q4e75i",
                            Email = "Amr@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "عمرو أسامة",
                            ImageUrl = "profiles/22337h37-556f-28ad-7ffg-7g10z9f5e14g.jpg",
                            LastName = "سعيد عبد القادر",
                            LockoutEnabled = false,
                            NationalId = "8899001122334455",
                            NormalizedEmail = "AMR@GMAIL.COM",
                            NormalizedUserName = "AMR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "078899001122",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57971r0f-5320-4033-86ag-8062f12fg67h",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Amr@gmail.com"
                        },
                        new
                        {
                            Id = "c90de12f-3g4h-5i6j-7k8l-9m0n1o2p3q4r",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f50sg7vv-d3i9-3d2d-8e12-e4e6f0r5f86j",
                            Email = "Lina@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "لينا رامي",
                            ImageUrl = "profiles/33448i48-667g-39be-8ggh-8h21a0g6f25h.png",
                            LastName = "خالد عبد السميع",
                            LockoutEnabled = false,
                            NationalId = "9900112233445566",
                            NormalizedEmail = "LINA@GMAIL.COM",
                            NormalizedUserName = "LINA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "079900112233",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "68082s1g-6431-5144-97bh-9173g23gh78i",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Lina@gmail.com"
                        },
                        new
                        {
                            Id = "d01ef23g-4h5i-6j7k-8l9m-0n1o2p3q4r5s",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "g61th8ww-e4j0-4e3e-9f23-f5f7g1s6g97k",
                            Email = "Ramy@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "رامي ناصر",
                            ImageUrl = "profiles/44559j59-778h-40cf-9hhi-9i32b1h7g36i.jpeg",
                            LastName = "محمد عبد العظيم",
                            LockoutEnabled = false,
                            NationalId = "0011223344556677",
                            NormalizedEmail = "RAMY@GMAIL.COM",
                            NormalizedUserName = "RAMY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "070011223344",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79193t2h-7542-6255-08ci-0284h34hi89j",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Ramy@gmail.com"
                        });
                });

            modelBuilder.Entity("Base.Domain.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "المستوي الاول"
                        },
                        new
                        {
                            Id = 2,
                            Name = "المستوي الثاني"
                        },
                        new
                        {
                            Id = 3,
                            Name = "المستوي الثالث"
                        },
                        new
                        {
                            Id = 4,
                            Name = "المستوي الرابع"
                        });
                });

            modelBuilder.Entity("Base.Domain.Entities.NFC_Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("NFC_Cards");
                });

            modelBuilder.Entity("Base.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Base.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Samester")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LevelId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0191d311-2918-7f76-bd8a-0bded8535075",
                            ConcurrencyStamp = "0191d311-2918-7f76-bd8a-0be08dd83078",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0191d311-2918-7f76-bd8a-0bdf740adff8",
                            ConcurrencyStamp = "0191d311-2918-7f76-bd8a-0be100f11384",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "0191d311-2918-7f76-bd8a-0bdf740adfA9",
                            ConcurrencyStamp = "0191d311-2918-7f76-bd8a-0bdf740adfA9",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "0191d311-2918-7f76-bd8a-0bdf740adff9",
                            ConcurrencyStamp = "0191d311-2918-7f76-bd8a-0bdf740adff9",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "e4b2f91d-9e12-4f4a-b3db-1b58fca15e66",
                            RoleId = "0191d311-2918-7f76-bd8a-0bded8535075"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Base.Domain.Entities.Attendence", b =>
                {
                    b.HasOne("Base.Domain.Entities.Student", "Student")
                        .WithMany("Attendences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Domain.Entities.Subject", "Subject")
                        .WithMany("Attendences")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Base.Domain.Entities.DepartmentLevel", b =>
                {
                    b.HasOne("Base.Domain.Entities.Department", "Department")
                        .WithMany("DepartmentLevels")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Domain.Entities.Level", "Level")
                        .WithMany("DepartmentLevels")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Base.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Base.Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("Doctors")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Base.Domain.Entities.NFC_Card", b =>
                {
                    b.HasOne("Base.Domain.Entities.Student", "Student")
                        .WithOne("NFC_Card")
                        .HasForeignKey("Base.Domain.Entities.NFC_Card", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Base.Domain.Entities.Student", b =>
                {
                    b.HasOne("Base.Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("Students")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Domain.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Domain.Entities.Level", "Level")
                        .WithMany("Students")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Department");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Base.Domain.Entities.Subject", b =>
                {
                    b.HasOne("Base.Domain.Entities.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Subjects")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Domain.Entities.Level", "Level")
                        .WithMany("Subjects")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Base.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Base.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Base.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Base.Domain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentLevels");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Base.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Base.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Base.Domain.Entities.Level", b =>
                {
                    b.Navigation("DepartmentLevels");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Base.Domain.Entities.Student", b =>
                {
                    b.Navigation("Attendences");

                    b.Navigation("NFC_Card");
                });

            modelBuilder.Entity("Base.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Attendences");
                });
#pragma warning restore 612, 618
        }
    }
}
